{% set name = "dvc-gs" %}
{% set version = "2.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c88f86c93d789cb880982cc3bdc00db619660f18760a3abdfb40f90233a87b41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - dvc
    - gcsfs >=2022.7.1

test:
  imports:
    - dvc_gs
  requires:
    - git
    - pip
  commands:
    - pip check
    - dvc version
    - dvc version | grep gs

about:
  home: https://github.com/iterative/dvc-gs
  summary: Google Storage plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
